# Generated by Django 3.1 on 2020-10-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='previous_vote',
            field=models.CharField(default='', max_length=200),
        ),
    ]
