# Generated by Django 3.1 on 2020-10-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_previous_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
